"use client";

import { 
  ExternalLink, BookOpen, TrendingUp, Clock, AlertCircle, 
  Target, Sparkles, ShieldCheck, Zap, BarChart2, LineChart as LineIcon,
  ChevronRight, BrainCircuit
} from "lucide-react";
import { 
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer 
} from "recharts";
import Sidebar from "@/components/layout/Sidebar";
import { ProgressBar, SectionHeader } from "@/components/shared";
import { mockCandidateProfile, mockTalentSignal, mockLearningRecs, mockMissionAttempts } from "@/lib/mock-data";

// Helper function for dynamic grading colors
const getGradeColor = (score: number) => {
  if (score < 50) return "#F59E0B"; // Yellow
  if (score <= 75) return "#334DAF"; // Blue
  return "#10B981"; // Green
};

// F5: Updated stage-based progression
const missionProgressionData = [
  { stage: "Skill Proof", score: 62 },
  { stage: "Judgment", score: 68 },
  { stage: "Learning", score: 82 },
];

const dimensionConfig = [
  { key: "skill_proof_score", label: "Skill Proof", score: 74, threshold: 80 },
  { key: "work_behavior_score", label: "Work Behavior", score: 45, threshold: 75 },
  { key: "learning_agility_score", label: "Learning Agility", score: 82, threshold: 75 },
  { key: "culture_fit_score", label: "Communication", score: 30, threshold: 70 },
];

export default function GapReportPage() {
  const profile = mockCandidateProfile;
  const weakDimensions = dimensionConfig.filter(d => d.score < d.threshold);
  const strongDimensions = dimensionConfig.filter(d => d.score >= d.threshold);

  return (
    <div className="flex min-h-screen" style={{ background: "#F0F3FA" }}>
      <Sidebar role="candidate" userName={profile.full_name} userLocation={profile.location} />
      
      <main className="flex-1 ml-0 lg:ml-64 p-4 sm:p-6 md:p-8 bg-grid relative overflow-x-hidden w-full">
        
        {/* Header - Laboratory Style */}
        <div className="mb-8 animate-fade-up">
          <p className="flex items-center gap-1.5" style={{ color: "#7096D1", fontFamily: "var(--font-syne, sans-serif)", fontWeight: 700, fontSize: "0.72rem", letterSpacing: "0.1em", textTransform: "uppercase" }}>
            <Sparkles size={14} className="text-[#334DAF]" /> System 3 · AI Evaluation Loop
          </p>
          <h1 style={{ fontFamily: "var(--font-syne, sans-serif)", fontWeight: 800, fontSize: "1.75rem", color: "#091F5C", letterSpacing: "-0.02em", marginTop: 4 }}>
            Evidence Analysis Report
          </h1>
          <p style={{ color: "#7096D1", fontSize: "0.85rem", fontFamily: "var(--font-dm-sans, sans-serif)", marginTop: 2, fontWeight: 500 }}>
            Post-Evaluation Diagnosis • Generated by Evidence Engine
          </p>
        </div>

        {/* F5 & F9: Mission Progression & AI Insight Panel */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 mb-8">
          
          {/* F5: Mission Build-up Card */}
          <div className="lg:col-span-8 bg-white p-6 rounded-2xl border border-[#D5DEEF] shadow-sm animate-fade-up">
            <div className="flex items-center justify-between mb-6">
              <SectionHeader title="Evaluation Build-up" subtitle="Score progression across mission sequence" />
              <div className="hidden sm:flex items-center gap-1 text-[#334DAF] font-bold text-xs bg-[#E8F2FE] px-2 py-1 rounded-lg">
                <BarChart2 size={14} /> Consistency: High
              </div>
            </div>
            <div className="h-[200px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={missionProgressionData}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#F0F3FA" />
                  <XAxis dataKey="stage" axisLine={false} tickLine={false} tick={{fill: '#7096D1', fontSize: 11, fontWeight: 600}} />
                  <Tooltip 
                    contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 25px rgba(9,31,92,0.1)' }}
                  />
                  <Line type="monotone" dataKey="score" stroke="#091F5C" strokeWidth={4} dot={{ r: 6, fill: "#091F5C", strokeWidth: 2, stroke: "#fff" }} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* F9: AI Learning Assistant Panel */}
          <div className="lg:col-span-4 bg-[#091F5C] p-6 rounded-2xl shadow-xl shadow-blue-900/20 animate-fade-up flex flex-col justify-between" style={{ animationDelay: "100ms" }}>
            <div>
              <div className="flex items-center gap-2 mb-4">
                <BrainCircuit size={20} className="text-[#D0E4FE]" />
                <p style={{ fontFamily: "var(--font-syne, sans-serif)", fontWeight: 700, color: "white", fontSize: "0.85rem", textTransform: "uppercase", letterSpacing: "0.05em" }}>Gemini Feedback</p>
              </div>
              <p className="text-[#D0E4FE] text-sm leading-relaxed mb-6 font-medium">
                "Excellent consistency across all missions. Your technical accuracy was high, though Judgment revealed a slight gap in Resource Management."
              </p>
            </div>
            
          </div>
        </div>

        {/* F2: Gap Overview Grid with Dynamic Colors */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          
          {/* Areas for Growth */}
          <div className="bg-white p-6 rounded-2xl border border-[#D5DEEF] shadow-sm animate-fade-up">
            <div className="flex items-center gap-2 mb-6">
              <div className="p-2 rounded-lg bg-[#E8F2FE]"><AlertCircle size={18} color="#334DAF" /></div>
              <p style={{ fontFamily: "var(--font-syne, sans-serif)", fontWeight: 800, color: "#091F5C", fontSize: "1rem" }}>Areas for Growth</p>
            </div>
            <div className="space-y-5">
              {weakDimensions.map(d => (
                <div key={d.key}>
                  <div className="flex justify-between mb-2">
                    <span style={{ fontFamily: "var(--font-syne, sans-serif)", fontWeight: 700, color: "#7096D1", fontSize: "0.8rem" }}>{d.label}</span>
                    <span style={{ fontFamily: "var(--font-syne, sans-serif)", fontWeight: 800, color: getGradeColor(d.score), fontSize: "0.85rem" }}>
                      {d.score > 0 ? `${d.score}%` : "0%"} <span style={{ color: "#D0E4FE", fontWeight: 500 }}>/ {d.threshold}</span>
                    </span>
                  </div>
                  <ProgressBar value={d.score} color={getGradeColor(d.score)} height={6} showLabel={false} />
                </div>
              ))}
            </div>
          </div>

          {/* Proven Strengths */}
          <div className="bg-white p-6 rounded-2xl border border-[#D5DEEF] shadow-sm animate-fade-up" style={{ animationDelay: "100ms" }}>
            <div className="flex items-center gap-2 mb-6">
              <div className="p-2 rounded-lg bg-[#F0FFF4]"><ShieldCheck size={18} color="#10B981" /></div>
              <p style={{ fontFamily: "var(--font-syne, sans-serif)", fontWeight: 800, color: "#091F5C", fontSize: "1rem" }}>Proven Strengths</p>
            </div>
            <div className="space-y-5">
              {strongDimensions.map(d => (
                <div key={d.key}>
                  <div className="flex justify-between mb-2">
                    <span style={{ fontFamily: "var(--font-syne, sans-serif)", fontWeight: 700, color: "#7096D1", fontSize: "0.8rem" }}>{d.label}</span>
                    <span style={{ fontFamily: "var(--font-syne, sans-serif)", fontWeight: 800, color: getGradeColor(d.score), fontSize: "0.85rem" }}>{d.score}%</span>
                  </div>
                  <ProgressBar value={d.score} color={getGradeColor(d.score)} height={6} showLabel={false} />
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* F8: Learning Bridge Recommendations */}
        <div className="bg-white p-6 rounded-2xl border border-[#D5DEEF] shadow-sm mb-8 animate-fade-up">
          <SectionHeader title="The Bridge" subtitle="Targeted resources to close identified gaps before your interview" />
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-6">
            {mockLearningRecs.map((rec) => (
              <div key={rec.id} className="space-y-4">
                <div className="p-4 rounded-2xl bg-[#F9FBFF] border border-[#D0E4FE]">
                  <p style={{ fontFamily: "var(--font-syne, sans-serif)", fontWeight: 800, color: "#334DAF", fontSize: "0.85rem", marginBottom: 6 }}>
                    {rec.dimension} Gap Analysis
                  </p>
                  <p style={{ color: "#7096D1", fontSize: "0.8rem", lineHeight: 1.6, fontWeight: 500 }}>
                    {rec.gap_diagnosis}
                  </p>
                </div>
                {rec.resources.map((resource) => (
                  <a key={resource.url} href={resource.url} target="_blank" rel="noopener noreferrer"
                    className="block p-4 rounded-2xl transition-all border border-[#D5DEEF] bg-white hover:border-[#334DAF] hover:shadow-md">
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-2">
                          <span style={{ background: "#E8F2FE", color: "#334DAF", border: "1px solid #D0E4FE", padding: "2px 8px", borderRadius: 6, fontSize: "0.6rem", fontWeight: 800, textTransform: "uppercase" }}>
                            {resource.platform}
                          </span>
                        </div>
                        <p style={{ fontFamily: "var(--font-syne, sans-serif)", fontWeight: 700, color: "#091F5C", fontSize: "0.85rem", marginBottom: 6 }}>
                          {resource.title}
                        </p>
                        <div className="flex items-center gap-1" style={{ color: "#7096D1", fontSize: "0.72rem", fontWeight: 600 }}>
                          <Clock size={12} /> {resource.estimated_hours}h estimated
                        </div>
                      </div>
                      <ExternalLink size={14} className="text-[#D0E4FE] group-hover:text-[#334DAF] shrink-0 mt-1" />
                    </div>
                  </a>
                ))}
              </div>
            ))}
          </div>
        </div>

        {/* F13: Mission Intelligence */}
        <div className="bg-white p-6 rounded-2xl border border-[#D5DEEF] shadow-sm animate-fade-up">
          <SectionHeader title="Evidence Details" subtitle="Detailed pattern feedback from your session" />
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
            {mockMissionAttempts.map((attempt) => (
              <div key={attempt.id} className="p-5 rounded-2xl bg-[#F9FBFF] border border-[#D5DEEF]">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <Target size={16} color="#334DAF" />
                    <h3 style={{ fontFamily: "var(--font-syne, sans-serif)", fontWeight: 800, color: "#091F5C", fontSize: "0.9rem" }}>{attempt.mission?.title}</h3>
                  </div>
                  <span className="text-sm font-bold" style={{ color: getGradeColor(attempt.total_score ?? 0) }}>{attempt.total_score}%</span>
                </div>
                <div className="space-y-3">
                  {attempt.improvements?.map((imp, i) => (
                    <div key={i} className="flex items-start gap-2.5">
                      <div className="w-1.5 h-1.5 rounded-full mt-1.5 shrink-0" style={{ background: getGradeColor(attempt.total_score ?? 0) }} />
                      <p style={{ color: "#7096D1", fontSize: "0.78rem", lineHeight: 1.5, fontWeight: 500 }}>{imp}</p>
                    </div>
                  ))}
                </div>
                <div className="mt-5 flex flex-wrap gap-2">
                   {attempt.strengths?.map((s, i) => (
                    <span key={i} className="px-2 py-1 rounded bg-white border border-[#D0E4FE] text-[10px] font-bold text-[#334DAF] uppercase">
                       {s}
                    </span>
                   ))}
                </div>
              </div>
            ))}
          </div>
        </div>

      </main>
    </div>
  );
}